stages:
  - build

build:
  stage: build
  image: rustlang/rust:nightly
  before_script:
    - apt-get update && apt-get install -y libgstreamer1.0-dev gstreamer1.0-pulseaudio libgl1-mesa-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good libssl-dev libgstreamer-plugins-base1.0-dev
  script:
    - cargo build --release
  cache:
    paths:
      - target/
  artifacts:
    paths:
      - target/release/soundvis
